### ISSUE TITLE
[Suggestion] Block tpa when in combat

### ISSUE THREAD

**Issue by gegtor** [F-Plugins/Teleporting#1]
There is currently only one opensource plugin that manages combat aka you have to wait if other players give you damage

https://github.com/RestoreMonarchyPlugins/Teleportation

It would be great if this plugin ported some of this functionality <3

**Comment by negrifelipe** [comment]
I will add that

**Comment by negrifelipe** [comment]
You can now download that feature here: https://github.com/F-Plugins/Teleporting/releases/tag/1.3.0

**Comment by negrifelipe** [comment]
Dont forget to tell me if everything works as expected

**Comment by gegtor** [comment]
Thank you! That was fast

I will test this and let you know in 1-2 days

**Comment by gegtor** [comment]
Quick question

https://github.com/RestoreMonarchyPlugins/Teleportation/issues/12

Does this plugin also stack or queue tpa requests? people abuse this as in the issue above

TPA queue could be configurable as true or false with a timer for example 30 seconds or something similar

**Comment by negrifelipe** [comment]
It stacks them but only 1 request per player

**Comment by negrifelipe** [comment]
They are stack and accept in order

**Comment by negrifelipe** [comment]
I will also add the tpa expire time when i get to home

**Comment by gegtor** [comment]
Oh if they accept the latest request this fixes the issue

Teleportation accepts the first one and players are often surprised

**Comment by negrifelipe** [comment]
I will add /tpa list and i will make the plugin use the latest tpa request

**Comment by gegtor** [comment]
Awesome <3

**Comment by negrifelipe** [comment]
I forgot that it isnt an issue because my plugin accepts tpas by using the player name
