### ISSUE TITLE
[Suggestion] Add rich text

### ISSUE THREAD

**Issue by gegtor** [F-Plugins/Teleporting#2]
Add support for TPA icons on different events like accept and deny or in combat in chat and allow for text styling and colors inside translations

**Comment by negrifelipe** [comment]
Rich text is already supported

**Comment by negrifelipe** [comment]
Try using <color=red>test</color> and you will see

**Comment by gegtor** [comment]
It's probably built in

Icons would be nice <3

**Comment by negrifelipe** [comment]
Good idea. I will add a config field for that and if its empty it will use the server icon

**Comment by gegtor** [comment]
Awesome

**Comment by negrifelipe** [comment]
On the next release (1.0.4) You will be able to use this
