### ISSUE TITLE
Teleport while the other party is dead

### ISSUE THREAD

**Issue by Whisperisgod** [F-Plugins/Teleporting#3]
**-AutoAcceptSameGroupRequests: Teleport request
being sent to the dead...! (e.g Request cannot be sent when the other party is dead..: )
-Teleport requests are not canceled after a while!
-TeleportCombatAllowed: Even if you cancel it, it works.**

**Comment by Whisperisgod** [comment]
why?

**Comment by Whisperisgod** [comment]
will it be fixed?

**Comment by negrifelipe** [comment]
its fixed

**Comment by Whisperisgod** [comment]
thx feli ♥
